import { MasteryPath } from '../mastery-path.model';

function triviaTarget(q: string, label = 'Practice trivia') {
  return {
    route: ['/coding'],
    queryParams: { tech: 'javascript', kind: 'trivia', q },
    label,
  };
}

function codingTarget(q: string, label = 'Practice coding') {
  return {
    route: ['/coding'],
    queryParams: { tech: 'javascript', kind: 'coding', q },
    label,
  };
}

const checkpointGuideTarget = {
  route: ['/guides', 'interview-blueprint', 'quiz'],
  label: 'Run checkpoint',
};

export const JAVASCRIPT_MASTERY_PATH: MasteryPath = {
  pathId: 'javascript-mastery-0-100',
  frameworkSlug: 'javascript-prep-path',
  availability: 'active',
  title: 'JavaScript Mastery Crash Track',
  subtitle: 'Guided 0 to 100 roadmap with trivia, output prediction, and coding drills.',
  description:
    'Build JavaScript fundamentals, then pressure-test execution with coding and checkpoint gates at each level.',
  theme: {
    accent: '#6cc2ff',
    accentSoft: '#2a3f57',
    surfaceTint: '#1b2b45',
  },
  scoring: {
    knowledgeWeight: 35,
    codingWeight: 65,
  },
  modules: [
    {
      id: 'foundations',
      title: 'Foundations',
      scoreBand: '0-20',
      summary: 'Primitives, values, coercion rules, and basic control flow.',
      learningGoals: [
        'Read and reason about values without guessing coercion behavior.',
        'Distinguish reference vs primitive updates in interview snippets.',
        'Write small utility transforms with clear runtime behavior.',
      ],
      commonMistakes: [
        'Relying on memorized tricks instead of deterministic value rules.',
        'Mixing strict and loose equality without clear intent.',
        'Skipping edge cases in basic loops and reducers.',
      ],
      unlockRule: {
        kind: 'none',
        label: 'Start here.',
      },
    },
    {
      id: 'functions-scope',
      title: 'Functions and Scope',
      scoreBand: '20-40',
      summary: 'Hoisting, TDZ, closure behavior, and function composition.',
      learningGoals: [
        'Explain scope resolution and closure capture precisely.',
        'Predict hoisting/TDZ behavior in short snippets.',
        'Implement closure and function utility patterns under time pressure.',
      ],
      commonMistakes: [
        'Hand-waving over TDZ errors instead of explaining timeline.',
        'Missing var loop capture bugs in async callbacks.',
        'Confusing arrow lexical bindings with regular function this.',
      ],
      unlockRule: {
        kind: 'checkpoint',
        checkpointItemId: 'cp-foundations',
        label: 'Complete Foundations checkpoint.',
      },
    },
    {
      id: 'objects-prototypes',
      title: 'Objects and Prototypes',
      scoreBand: '40-55',
      summary: 'Object model internals, prototypes, classes, and this binding.',
      learningGoals: [
        'Trace property lookup through the prototype chain.',
        'Reason about class sugar vs prototype mechanisms.',
        'Implement foundational object utilities without libraries.',
      ],
      commonMistakes: [
        'Treating class syntax as a separate inheritance model.',
        'Incorrect this assumptions in callback-heavy code.',
        'Ignoring property descriptors and mutability constraints.',
      ],
      unlockRule: {
        kind: 'checkpoint',
        checkpointItemId: 'cp-functions-scope',
        label: 'Complete Functions and Scope checkpoint.',
      },
    },
    {
      id: 'async-event-loop',
      title: 'Async and Event Loop',
      scoreBand: '55-70',
      summary: 'Scheduling model, promises, async patterns, and cancellation-safe flows.',
      learningGoals: [
        'Predict execution order using stack, microtasks, and macrotasks.',
        'Choose the right Promise combinator for failure semantics.',
        'Write robust async wrappers with timeout and retry controls.',
      ],
      commonMistakes: [
        'Mislabeling queue behavior during output explanations.',
        'Swallowing errors with broad try/catch blocks.',
        'Running sequential awaits where parallel orchestration is required.',
      ],
      unlockRule: {
        kind: 'checkpoint',
        checkpointItemId: 'cp-objects-prototypes',
        label: 'Complete Objects and Prototypes checkpoint.',
      },
    },
    {
      id: 'browser-practice',
      title: 'Browser Practice',
      scoreBand: '70-85',
      summary: 'DOM events, network boundaries, and interview-grade browser utilities.',
      learningGoals: [
        'Use propagation and delegation rules correctly in UI debugging.',
        'Design safe fetch behavior with abort and retry options.',
        'Implement high-signal browser utilities like debounce/throttle.',
      ],
      commonMistakes: [
        'Incorrect event phase assumptions in nested handlers.',
        'Missing cancellation behavior for in-flight network requests.',
        'Implementing debounce/throttle without leading/trailing trade-off reasoning.',
      ],
      unlockRule: {
        kind: 'checkpoint',
        checkpointItemId: 'cp-async-event-loop',
        label: 'Complete Async and Event Loop checkpoint.',
      },
    },
    {
      id: 'mastery',
      title: 'Mastery',
      scoreBand: '85-100',
      summary: 'Performance, architecture edges, and capstone implementation challenges.',
      learningGoals: [
        'Diagnose memory/performance risks in production-like scenarios.',
        'Defend architecture trade-offs with concise technical reasoning.',
        'Ship complete utility implementations without hidden edge-case failures.',
      ],
      commonMistakes: [
        'Over-optimizing before proving correctness.',
        'Skipping explanation of trade-offs under interview follow-ups.',
        'Ignoring cleanup paths that cause memory leaks over time.',
      ],
      unlockRule: {
        kind: 'checkpoint',
        checkpointItemId: 'cp-browser-practice',
        label: 'Complete Browser Practice checkpoint.',
      },
    },
  ],
  items: [
    {
      id: 'js-foundations-primitives-trivia',
      moduleId: 'foundations',
      type: 'trivia',
      title: 'Primitives vs references',
      summary: 'Explain stack-style value copying vs reference-style mutation behavior.',
      difficulty: 'easy',
      estimatedMinutes: 8,
      xp: 10,
      target: triviaTarget('primitives references'),
    },
    {
      id: 'js-foundations-coercion-trivia',
      moduleId: 'foundations',
      type: 'trivia',
      title: 'Coercion rules that actually matter',
      summary: 'Reason about Number/String/Boolean coercion with concrete edge cases.',
      difficulty: 'easy',
      estimatedMinutes: 10,
      xp: 10,
      target: triviaTarget('coercion equality'),
    },
    {
      id: 'js-foundations-falsy-trivia',
      moduleId: 'foundations',
      type: 'trivia',
      title: 'Truthy and falsy checkpoints',
      summary: 'List all falsy values and explain why objects stay truthy.',
      difficulty: 'easy',
      estimatedMinutes: 6,
      xp: 8,
      target: triviaTarget('truthy falsy values'),
    },
    {
      id: 'js-foundations-equality-predict',
      moduleId: 'foundations',
      type: 'predict',
      title: 'Predict output: equality traps',
      summary: 'Predict results for loose/strict comparisons before running code.',
      difficulty: 'easy',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('equality output prediction', 'Run prediction drills'),
    },
    {
      id: 'js-foundations-fizzbuzz-coding',
      moduleId: 'foundations',
      type: 'coding',
      title: 'Coding drill: control flow reliability',
      summary: 'Implement core loop logic cleanly with deterministic branching.',
      difficulty: 'easy',
      estimatedMinutes: 15,
      xp: 18,
      target: codingTarget('loop transform'),
    },
    {
      id: 'js-foundations-frequency-map-coding',
      moduleId: 'foundations',
      type: 'coding',
      title: 'Coding drill: frequency map',
      summary: 'Build a reusable counting helper over arrays and strings.',
      difficulty: 'easy',
      estimatedMinutes: 18,
      xp: 22,
      target: codingTarget('frequency map'),
    },
    {
      id: 'cp-foundations',
      moduleId: 'foundations',
      type: 'checkpoint',
      title: 'Checkpoint: Foundations gate',
      summary: 'Pass a short mixed drill before unlocking Functions and Scope.',
      difficulty: 'easy',
      estimatedMinutes: 12,
      xp: 30,
      target: checkpointGuideTarget,
    },

    {
      id: 'js-scope-hoisting-trivia',
      moduleId: 'functions-scope',
      type: 'trivia',
      title: 'Hoisting without myths',
      summary: 'State exactly what is hoisted and what is not for var/let/const/functions.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('hoisting var let const'),
    },
    {
      id: 'js-scope-tdz-predict',
      moduleId: 'functions-scope',
      type: 'predict',
      title: 'Predict output: Temporal Dead Zone',
      summary: 'Identify TDZ runtime failures from small snippets.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('temporal dead zone output', 'Run prediction drills'),
    },
    {
      id: 'js-scope-closure-trivia',
      moduleId: 'functions-scope',
      type: 'trivia',
      title: 'Closure fundamentals',
      summary: 'Explain lexical scope capture with practical use cases.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('closures lexical scope'),
    },
    {
      id: 'js-scope-var-loop-predict',
      moduleId: 'functions-scope',
      type: 'predict',
      title: 'Predict output: var loop callbacks',
      summary: 'Explain why var/let differ in asynchronous loop callbacks.',
      difficulty: 'intermediate',
      estimatedMinutes: 12,
      xp: 16,
      target: triviaTarget('var let loop async', 'Run prediction drills'),
    },
    {
      id: 'js-scope-closure-counter-coding',
      moduleId: 'functions-scope',
      type: 'coding',
      title: 'Coding drill: closure counter',
      summary: 'Implement encapsulated state with function factories.',
      difficulty: 'intermediate',
      estimatedMinutes: 20,
      xp: 24,
      target: codingTarget('closure counter'),
    },
    {
      id: 'js-scope-custom-bind-coding',
      moduleId: 'functions-scope',
      type: 'coding',
      title: 'Coding drill: custom bind',
      summary: 'Recreate bind semantics for interview-level understanding.',
      difficulty: 'intermediate',
      estimatedMinutes: 24,
      xp: 28,
      target: codingTarget('custom bind polyfill'),
    },
    {
      id: 'cp-functions-scope',
      moduleId: 'functions-scope',
      type: 'checkpoint',
      title: 'Checkpoint: Functions and Scope gate',
      summary: 'Validate closures/hoisting under mixed trivia + coding pressure.',
      difficulty: 'intermediate',
      estimatedMinutes: 14,
      xp: 35,
      target: checkpointGuideTarget,
    },

    {
      id: 'js-objects-prototype-trivia',
      moduleId: 'objects-prototypes',
      type: 'trivia',
      title: 'Prototype chain lookup',
      summary: 'Trace property resolution across prototype boundaries.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('prototype chain lookup'),
    },
    {
      id: 'js-objects-class-vs-prototype-trivia',
      moduleId: 'objects-prototypes',
      type: 'trivia',
      title: 'Class syntax vs prototype model',
      summary: 'Differentiate syntax sugar from runtime behavior.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('class vs prototype'),
    },
    {
      id: 'js-objects-this-binding-predict',
      moduleId: 'objects-prototypes',
      type: 'predict',
      title: 'Predict output: this binding',
      summary: 'Apply call-site rules for this in regular vs arrow functions.',
      difficulty: 'intermediate',
      estimatedMinutes: 12,
      xp: 18,
      target: triviaTarget('this binding output', 'Run prediction drills'),
    },
    {
      id: 'js-objects-descriptor-trivia',
      moduleId: 'objects-prototypes',
      type: 'trivia',
      title: 'Property descriptors and mutability',
      summary: 'Use writable/configurable/enumerable flags correctly.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('property descriptors object define property'),
    },
    {
      id: 'js-objects-polyfill-new-coding',
      moduleId: 'objects-prototypes',
      type: 'coding',
      title: 'Coding drill: new operator polyfill',
      summary: 'Implement object creation with prototype wiring manually.',
      difficulty: 'hard',
      estimatedMinutes: 26,
      xp: 30,
      target: codingTarget('new operator polyfill'),
    },
    {
      id: 'js-objects-deep-freeze-coding',
      moduleId: 'objects-prototypes',
      type: 'coding',
      title: 'Coding drill: deep freeze utility',
      summary: 'Recursively enforce immutability over nested objects.',
      difficulty: 'hard',
      estimatedMinutes: 24,
      xp: 30,
      target: codingTarget('deep freeze object utility'),
    },
    {
      id: 'cp-objects-prototypes',
      moduleId: 'objects-prototypes',
      type: 'checkpoint',
      title: 'Checkpoint: Objects and Prototypes gate',
      summary: 'Confirm this/prototype reasoning before async-heavy modules.',
      difficulty: 'intermediate',
      estimatedMinutes: 14,
      xp: 35,
      target: checkpointGuideTarget,
    },

    {
      id: 'js-async-event-loop-predict',
      moduleId: 'async-event-loop',
      type: 'predict',
      title: 'Predict output: event loop ordering',
      summary: 'Order logs across sync code, microtasks, and timers.',
      difficulty: 'hard',
      estimatedMinutes: 14,
      xp: 20,
      target: triviaTarget('event loop output order', 'Run prediction drills'),
    },
    {
      id: 'js-async-microtask-macrotask-trivia',
      moduleId: 'async-event-loop',
      type: 'trivia',
      title: 'Microtask vs macrotask rules',
      summary: 'Explain scheduling and starvation risks succinctly.',
      difficulty: 'hard',
      estimatedMinutes: 12,
      xp: 16,
      target: triviaTarget('microtask macrotask differences'),
    },
    {
      id: 'js-async-promise-all-family-trivia',
      moduleId: 'async-event-loop',
      type: 'trivia',
      title: 'Promise combinator trade-offs',
      summary: 'Choose all/allSettled/race/any by failure behavior.',
      difficulty: 'hard',
      estimatedMinutes: 12,
      xp: 16,
      target: triviaTarget('promise all settled race any'),
    },
    {
      id: 'js-async-error-handling-trivia',
      moduleId: 'async-event-loop',
      type: 'trivia',
      title: 'Async error handling strategy',
      summary: 'Avoid swallowed failures while keeping flows readable.',
      difficulty: 'hard',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('async await error handling'),
    },
    {
      id: 'js-async-retry-wrapper-coding',
      moduleId: 'async-event-loop',
      type: 'coding',
      title: 'Coding drill: retry wrapper',
      summary: 'Implement retry with bounded attempts and backoff behavior.',
      difficulty: 'hard',
      estimatedMinutes: 28,
      xp: 34,
      target: codingTarget('promise retry wrapper'),
    },
    {
      id: 'js-async-timeout-wrapper-coding',
      moduleId: 'async-event-loop',
      type: 'coding',
      title: 'Coding drill: timeout wrapper',
      summary: 'Race async work against timeout with clean rejection semantics.',
      difficulty: 'hard',
      estimatedMinutes: 24,
      xp: 30,
      target: codingTarget('promise timeout wrapper'),
    },
    {
      id: 'cp-async-event-loop',
      moduleId: 'async-event-loop',
      type: 'checkpoint',
      title: 'Checkpoint: Async and Event Loop gate',
      summary: 'Pass mixed async reasoning before browser-focused drills.',
      difficulty: 'hard',
      estimatedMinutes: 16,
      xp: 40,
      target: checkpointGuideTarget,
    },

    {
      id: 'js-browser-event-propagation-trivia',
      moduleId: 'browser-practice',
      type: 'trivia',
      title: 'Event propagation model',
      summary: 'Capture, target, bubble phases and practical debugging.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('event propagation capture bubble'),
    },
    {
      id: 'js-browser-delegation-trivia',
      moduleId: 'browser-practice',
      type: 'trivia',
      title: 'Event delegation trade-offs',
      summary: 'Choose delegation boundaries for dynamic lists safely.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('event delegation dom'),
    },
    {
      id: 'js-browser-fetch-abort-trivia',
      moduleId: 'browser-practice',
      type: 'trivia',
      title: 'Abort in-flight requests',
      summary: 'Use AbortController to prevent stale network writes.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('abortcontroller fetch cancellation'),
    },
    {
      id: 'js-browser-cors-trivia',
      moduleId: 'browser-practice',
      type: 'trivia',
      title: 'CORS basics for frontend interviews',
      summary: 'Explain preflight, allowed origins, and credentials constraints.',
      difficulty: 'intermediate',
      estimatedMinutes: 10,
      xp: 12,
      target: triviaTarget('cors preflight credentials'),
    },
    {
      id: 'js-browser-debounce-coding',
      moduleId: 'browser-practice',
      type: 'coding',
      title: 'Coding drill: debounce',
      summary: 'Implement trailing and optional leading behavior correctly.',
      difficulty: 'intermediate',
      estimatedMinutes: 20,
      xp: 24,
      target: codingTarget('debounce function'),
    },
    {
      id: 'js-browser-throttle-coding',
      moduleId: 'browser-practice',
      type: 'coding',
      title: 'Coding drill: throttle',
      summary: 'Control execution rate while preserving user intent.',
      difficulty: 'intermediate',
      estimatedMinutes: 20,
      xp: 24,
      target: codingTarget('throttle function'),
    },
    {
      id: 'js-browser-search-list-coding',
      moduleId: 'browser-practice',
      type: 'coding',
      title: 'Coding drill: searchable list',
      summary: 'Combine delegation and debounced input for a realistic UI task.',
      difficulty: 'hard',
      estimatedMinutes: 24,
      xp: 28,
      target: codingTarget('dom searchable list'),
    },
    {
      id: 'cp-browser-practice',
      moduleId: 'browser-practice',
      type: 'checkpoint',
      title: 'Checkpoint: Browser Practice gate',
      summary: 'Validate browser APIs and utility implementation quality.',
      difficulty: 'hard',
      estimatedMinutes: 16,
      xp: 40,
      target: checkpointGuideTarget,
    },

    {
      id: 'js-mastery-memory-leak-trivia',
      moduleId: 'mastery',
      type: 'trivia',
      title: 'Memory leak diagnosis',
      summary: 'Identify leak roots in listeners, closures, and retained DOM nodes.',
      difficulty: 'hard',
      estimatedMinutes: 12,
      xp: 16,
      target: triviaTarget('memory leak browser javascript'),
    },
    {
      id: 'js-mastery-immutability-tradeoffs-trivia',
      moduleId: 'mastery',
      type: 'trivia',
      title: 'Immutability trade-offs',
      summary: 'Balance readability, safety, and performance in state updates.',
      difficulty: 'hard',
      estimatedMinutes: 12,
      xp: 16,
      target: triviaTarget('immutability tradeoffs performance'),
    },
    {
      id: 'js-mastery-module-systems-trivia',
      moduleId: 'mastery',
      type: 'trivia',
      title: 'ESM vs CommonJS in practice',
      summary: 'Explain import/export execution and interop behavior.',
      difficulty: 'hard',
      estimatedMinutes: 10,
      xp: 14,
      target: triviaTarget('esm commonjs differences'),
    },
    {
      id: 'js-mastery-map-filter-reduce-coding',
      moduleId: 'mastery',
      type: 'coding',
      title: 'Coding drill: map/filter/reduce polyfills',
      summary: 'Implement core array method behavior and callback contracts.',
      difficulty: 'hard',
      estimatedMinutes: 30,
      xp: 36,
      target: codingTarget('map filter reduce polyfill'),
    },
    {
      id: 'js-mastery-lru-cache-coding',
      moduleId: 'mastery',
      type: 'coding',
      title: 'Coding drill: LRU cache',
      summary: 'Build eviction strategy with predictable O(1)-style operations.',
      difficulty: 'hard',
      estimatedMinutes: 34,
      xp: 40,
      target: codingTarget('lru cache implementation'),
    },
    {
      id: 'js-mastery-reactive-store-coding',
      moduleId: 'mastery',
      type: 'coding',
      title: 'Coding drill: tiny reactive store',
      summary: 'Design subscribe/unsubscribe/update semantics with cleanup safety.',
      difficulty: 'hard',
      estimatedMinutes: 32,
      xp: 38,
      target: codingTarget('reactive store implementation'),
    },
    {
      id: 'cp-mastery-final',
      moduleId: 'mastery',
      type: 'checkpoint',
      title: 'Final checkpoint: JavaScript Mastery pass',
      summary: 'Run a final mixed simulation and capture weak spots for next cycle.',
      difficulty: 'hard',
      estimatedMinutes: 20,
      xp: 50,
      target: {
        route: ['/guides', 'interview-blueprint', 'javascript-interviews'],
        label: 'Run final simulation',
      },
    },
  ],
};
