import { SENTRY_DSN, SENTRY_RELEASE, SENTRY_TRACES_SAMPLE_RATE } from './sentry.env';

export const environment = {
    production: false,
    dataVersion: "2025-08-19a",
    apiBase: "/api", // 👈 proxy to http://localhost:3001/api
    frontendBase: "",
    cdnBaseUrl: '',
    cdnEnabled: false,
    sentryDsn: SENTRY_DSN,
    sentryRelease: SENTRY_RELEASE,
    sentryTracesSampleRate: SENTRY_TRACES_SAMPLE_RATE,
    PAYMENTS_PROVIDER: 'lemonsqueezy',
    PAYMENTS_MODE: 'test',
    GUMROAD_MONTHLY_URL: 'https://frontendatlas.gumroad.com/l/xsoew',
    GUMROAD_QUARTERLY_URL: 'https://frontendatlas.gumroad.com/l/rwsapy',
    GUMROAD_ANNUAL_URL: 'https://frontendatlas.gumroad.com/l/rwurwg',
    GUMROAD_MANAGE_URL: 'https://gumroad.com/subscriptions',
    LEMONSQUEEZY_MONTHLY_URL: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/634cd291-623f-4358-9ec3-9ef79e0a3bee',
    LEMONSQUEEZY_QUARTERLY_URL: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/00215452-82d4-40c3-ba10-4ccc879bf0d0',
    LEMONSQUEEZY_ANNUAL_URL: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/52ed1d27-23a1-410b-b9d6-873d7ecc6ced',
    LEMONSQUEEZY_LIFETIME_URL: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/2ec8ac68-4d40-4b2d-a6b9-cc3ca4ec63d7',
    LEMONSQUEEZY_MANAGE_URL: '',
    LEMONSQUEEZY_MONTHLY_URL_TEST: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/634cd291-623f-4358-9ec3-9ef79e0a3bee',
    LEMONSQUEEZY_QUARTERLY_URL_TEST: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/00215452-82d4-40c3-ba10-4ccc879bf0d0',
    LEMONSQUEEZY_ANNUAL_URL_TEST: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/52ed1d27-23a1-410b-b9d6-873d7ecc6ced',
    LEMONSQUEEZY_LIFETIME_URL_TEST: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/2ec8ac68-4d40-4b2d-a6b9-cc3ca4ec63d7',
    LEMONSQUEEZY_MANAGE_URL_TEST: '',
    LEMONSQUEEZY_MONTHLY_URL_LIVE: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/634cd291-623f-4358-9ec3-9ef79e0a3bee',
    LEMONSQUEEZY_QUARTERLY_URL_LIVE: 'https://frontendatlas.lemonsqueezy.com/checkout/buy/00215452-82d4-40c3-ba10-4ccc879bf0d0',
    LEMONSQUEEZY_ANNUAL_URL_LIVE: '',
    LEMONSQUEEZY_LIFETIME_URL_LIVE: '',
    LEMONSQUEEZY_MANAGE_URL_LIVE: '',
    STRIPE_MONTHLY_URL: '',
    STRIPE_QUARTERLY_URL: '',
    STRIPE_ANNUAL_URL: '',
    STRIPE_MANAGE_URL: '',
};
