      - name: Build Angular app
        run: |
          npx ng build --configuration production --base-href=/uberfrontend/
          ls -R dist/uberfrontend

      - name: Copy 404
        run: cp dist/uberfrontend/browser/index.html dist/uberfrontend/browser/404.html

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/uberfrontend/browser --no-silent