name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          echo "Running Angular Build..."
          npx ng build --configuration production --base-href=/uberfrontend/
          echo "Build output:"
          ls -la dist/uberfrontend

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/uberfrontend