name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build Angular app
        run: |
          npx ng build --configuration production --base-href=/uberfrontend/
          ls -R dist/uberfrontend

      - name: Copy 404
        run: cp dist/uberfrontend/browser/index.html dist/uberfrontend/browser/404.html

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/uberfrontend/browser --no-silent